### ISSUE TITLE
Distribute portals randomly

### ISSUE THREAD

**Issue by bcaddy** [bcaddy/Random-Walk-RPI#9]

**Comment by jrasband** [comment]
On my branch, there's a file called "Receptors.py" which has a "seedReceptors" function. This function takes a "world" object as input (a placeholder for information about the simulation) and returns a matrix with ones indicating the positions of receptors and zeroes everywhere else.

I tried to add plenty of comments to make it clear how my code works.

I'm marking this as closed, so comment on this if there's more functionality that you need added.
